Updated list for FO4 Patch 1.9 and the hi-res DLC package.
loot/fallout4 pull request #35
Opened 2017-02-14 06:21 UTC by Arthmoor

2017-02-14 07:47 UTC, WrinklyNinja commented
For the high-res DLC package, the same metadata got submitted in #34, but @Freso and I aren't sure what's necessary. Does the high-res package contain DLC textures too?

2017-02-14 17:16 UTC, Freso requested changes
Basically what @WrinklyNinja said, plus some [nit picking](http://chris.beams.io/posts/git-commit/). 😇

2017-02-14 17:16 UTC, Freso commented on masterlist.yaml
> +      - 'https://afkmods.iguanadons.net/index.php?/files/file/1765-unofficial-fallout-4-patch/'
This seems like it's semantically a different change than any of the others. Perhaps it could be in its own commit?

2017-02-14 17:16 UTC, Freso commented on masterlist.yaml
> +      - 'DLCNukaWorld.esm'
As @WrinklyNinja said, perhaps leave this out for now until we figure out what to do with it? There's also already another PR already just for this specific change: #34

2017-07-06 16:07 UTC, Freso commented
Thanks for your contribution! Every change in this PR is deprecated or added via other PRs/commits by now though, so I'll just close this now.

2017-07-06 16:07 UTC, closed without merging