Better Settlers
loot/fallout4 pull request #38
Opened 2017-04-04 04:34 UTC by ghostsquad

After reading the [mod description](http://www.nexusmods.com/fallout4/mods/4772), I decided that it would be really useful to have this in loot if it wasn't already. I tested this locally (including installing the mod multiple times with different options to ensure I got all the correct filenames).

2017-04-04 06:54 UTC, Ortham requested changes
If you get rid of the `# Better Settlers` and `# End Better Settlers` lines, I'll merge this. The comments aren't really useful and risk becoming outdated.

2017-04-04 09:13 UTC, Freso requested changes
Looks good apart from the few unneeded lines. 👍

2017-04-04 09:13 UTC, Freso commented on masterlist.yaml
> +
As @WrinklyNinja said, please remove these three lines…

2017-04-04 09:13 UTC, Freso commented on masterlist.yaml
> +    # End Better Settlers
And these two lines.

2017-04-06 02:39 UTC, ghostsquad commented
I've made the changes requested, please review.

2017-04-06 07:30 UTC, merged

2017-04-06 07:31 UTC, Ortham commented
LGTM, thanks.