Add Moddable Goodfeels
loot/fallout4 pull request #408
Opened 2021-12-21 19:22 UTC by IllusiveMan196

Add mod, location, cleaning data

2021-12-21 19:33 UTC, IllusiveMan196 commented
Well, ok. It adds ability to mod Goodfeels, but fix is necessary anyway, so in fixes it goes.

2021-12-22 08:39 UTC, sibir-ine requested changes

2021-12-22 08:39 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/fallout4/mods/11500' ]
Trailing slash for consistency:

```suggestion
    url: [ 'https://www.nexusmods.com/fallout4/mods/11500/' ]
```

2021-12-22 08:39 UTC, sibir-ine commented on masterlist.yaml
> +        util: 'FO4Edit v4.0.4'
We exclude cleaning data for dirty plugins after they're cleaned due to volatility in the checksum.

```suggestion
```

2021-12-22 20:05 UTC, sibir-ine approved these changes

2021-12-22 20:07 UTC, merged