Add more SS2 checking
loot/fallout4 pull request #445
Opened 2022-04-13 06:56 UTC by dm703

2022-04-13 07:05 UTC, sibir-ine commented
Unless there's a unifying theme (e.g., Bash Tags, cleaning data), unrelated edits to different mods (including related mods like patches or add-ons hosted on separate pages) should be made in separate PRs. In this case, the SS2 incompatibility changes would be made in one PR & the SS2 Chapter 2 addition in another.

2022-04-13 07:18 UTC, dm703 commented
Currently, my workflow is to delete my fork after each PR has been merged and start fresh.
This limits me to 1 PR per day (or so).
The unifying theme here is to get the masterlist updated with currently known info with respect to SS2.
SS2 is effectively an entire ecosystem (like Horizon or FROST).
Perhaps it should even have its own group (but that is probably a Discord discussion).
I agree that PRs that I need to submit that pertain to F04 areas other than SS2 need to be on separate PRs.

2022-04-13 07:31 UTC, sibir-ine commented
If you create new branches off of your `v0.18` branch & submit pull requests from them, you can delete them after they're merged & just pull from upstream to update your `v0.18`. That way, you wouldn't need to delete your fork, & you could submit multiple PRs at the same time (merge conflicts can be resolved on the website fairly easily). If you need help with the process, we can walk you through it in the `#dev-questions` channel in the Discord.

2022-04-13 08:23 UTC, dm703 commented
Does that mean the effort in creating this PR has been wasted and this PR should be abandoned?

2022-04-13 08:27 UTC, sibir-ine commented
No, you can just undo the changes for one of the mods in another commit & submit them in a separate PR.

2022-04-15 00:31 UTC, sibir-ine requested changes

2022-04-15 00:31 UTC, sibir-ine commented on masterlist.yaml
> +
This can be removed from this PR since you've added it in #446.

```suggestion
```

2022-04-15 22:39 UTC, sibir-ine approved these changes

2022-04-15 22:47 UTC, sibir-ine commented on masterlist.yaml
> +        display: 'Conquest - Build New Settlements and Camping'
Sorry, forgot to check that the incompatibilities were alphabetically sorted:

```suggestion
      - name: 'Conquest.esp'
        display: 'Conquest - Build New Settlements and Camping'
      - name: 'SimSettlements.esm'
        display: 'Sim Settlements'
```

2022-04-15 22:59 UTC, merged