Add SS2 Chapter 2 - Gun for Hire patch
loot/fallout4 pull request #446
Opened 2022-04-14 23:46 UTC by dm703

2022-04-15 23:12 UTC, sibir-ine requested changes
Conflicts need to be resolved, but it looks good otherwise.

2022-04-16 03:57 UTC, dm703 commented
I click on Resolve Conflicts, but there doesn't appear to be any action I can take.
It simply shows the conflict, but no way to perform any useful action, like 'Resolve'.

2022-04-16 04:34 UTC, sibir-ine commented
You have to manually resolve the conflict by editing the file it presents you with. If the conflict doesn't automatically center on your screen, click __Next__ in the top-right corner to navigate to it. The text between `<<<<<<< Your-branch-name` & `=======` is from your branch & between `=======` & `>>>>>>> v0.18` is from the online repo. In this case, since your branch is outdated, you can just remove the text from your branch & the conflict markers (the equal signs, arrows, & branch names), then mark it as resolved.

2022-04-16 07:44 UTC, sibir-ine approved these changes

2022-04-16 07:50 UTC, merged