Add Better Landscape Grass
loot/fallout4 pull request #547
Opened 2023-08-04 21:05 UTC by DoubleYouC

* Add plugin
  * To 'AudioVisual - Fixes' section.

* Add location
  * [https://www.nexusmods.com/fallout4/mods/38360/](https://www.nexusmods.com/fallout4/mods/38360/)

* Assign 'Low Priority Overrides' group
  * Modifies grass and landscape records. Load before mods that have precombine data and after mods that do not have precombine data.

* Add cleaning data

2023-08-04 21:59 UTC, sibir-ine requested changes
Besides the suggestions, what version is this cleaning data for? I'm assuming the latest, v3.1?

2023-08-04 21:59 UTC, sibir-ine commented on masterlist.yaml
> +    url: ["https://www.nexusmods.com/fallout4/mods/38360/" ]
The masterlists use single-quotes to encapsulate strings. You can also add a name to display the link with in the UI:

```suggestion
    url:
      - link: 'https://www.nexusmods.com/fallout4/mods/38360/'
        name: 'Better Landscape Grass'
```

2023-08-04 21:59 UTC, sibir-ine commented on masterlist.yaml
>    - name: 'CliffsEdgeHotelWindowFix.esp'
There are some trailing spaces here:

```suggestion
        itm: 191

  - name: 'CliffsEdgeHotelWindowFix.esp'
```

2023-08-04 22:25 UTC, DoubleYouC commented
> Besides the suggestions, what version is this cleaning data for? I'm assuming the latest, v3.1?

Yes. These are for the latest v3.1 main file.

2023-08-06 00:04 UTC, sibir-ine approved these changes

2023-08-06 00:07 UTC, merged