Add Vault 81 Close Door
loot/fallout4 pull request #552
Opened 2023-08-05 20:40 UTC by DoubleYouC

* Add plugin
  * To 'Gameplay' section

* Add location
  * [https://www.nexusmods.com/fallout4/mods/12723/](https://www.nexusmods.com/fallout4/mods/12723/)

* Assign 'Fixes' group
  * Modifies 3 placed references in Vault 81's interior cell. The rest are new records.

* Add cleaning data for version 1.0.2

2023-08-06 05:59 UTC, sibir-ine requested changes

2023-08-06 05:59 UTC, sibir-ine commented on masterlist.yaml
> +  - name: 'Vault81Etiquette.esp'
There are trailing spaces here:

```suggestion
        udr: 9

  - name: 'Vault81Etiquette.esp'
```

2023-08-06 20:16 UTC, DoubleYouC commented
I believe I finally have VSCode setup to trim the trailing spaces now. Thanks for finding these for me.

2023-08-09 09:02 UTC, sibir-ine approved these changes

2023-08-09 09:03 UTC, merged