Add Extra Icons for FIS
loot/fallout4 pull request #565
Opened 2023-08-11 13:34 UTC by such-dev

2023-08-20 12:25 UTC, DoubleYouC commented
I had a discussion with m8r98a4f2﻿  on Collective Modding Discord about this. It is most likely incorrect for the plugin to go after a dynamic patch such as created by Complex Sorter, especially since the mod seems to contain Complex Sorter plugin files.

2023-08-23 20:18 UTC, pStyl3 requested changes

2023-08-23 20:18 UTC, pStyl3 commented on masterlist.yaml
> +      - 'M8r Complex Sorter.esp'
The load after for `M8r Complex Sorter.esp` needs to be removed, see [this comment on Discord](https://discord.com/channels/830436661736243230/915413649638707251/1142802194777772162) from `m8r98a4f2`, author of the Complex Sorter.

2023-08-25 05:50 UTC, pStyl3 approved these changes

2023-08-25 05:51 UTC, merged

2023-08-25 05:51 UTC, pStyl3 commented
Thanks