changed BetterSettlers order according to requirements
loot/fallout4 pull request #72
Opened 2018-06-29 13:12 UTC by soyasoya5

2018-06-29 16:17 UTC, Ortham requested changes
Thanks for contributing, I've commented on a few issues.

2018-06-29 16:17 UTC, WrinklyNinja commented on masterlist.yaml
> +      - 'Scrap Everything.+\.esp'
After entries need to be exact plugin names, that regex (and the others in your commit) won't be used as a regex.

2018-06-29 16:17 UTC, WrinklyNinja commented on masterlist.yaml
> +      - 'BetterSettlersCCAPack.+\.esp'
See my earlier comment, you'll need to list the exact plugins instead.

2018-06-29 16:17 UTC, WrinklyNinja commented on masterlist.yaml
> +      - 'BetterSettlersCCAPack.+\.esp'
See my earlier comment, you'll need to list the exact plugins instead.

2018-06-30 10:47 UTC, soyasoya5 commented
Hi, thanks for the comments. I've made the requested changes and squashed commits.

2018-06-30 11:58 UTC, Ortham approved these changes

2018-06-30 11:58 UTC, merged

2018-06-30 11:58 UTC, WrinklyNinja commented
Thanks!