Adds AAF_RSE
loot/fallout4 pull request #89
Opened 2018-11-07 10:53 UTC by RowanSkie

Adds Loverslab mod: AAF RSE. Nothing else.

2018-11-07 13:25 UTC, Freso requested changes

2018-11-07 13:25 UTC, Freso commented on masterlist.yaml
> -
Is there a reason you're removing this newline? Seems like this line would still be good to (visually) separate the alternate start mods from the `FO4Merged.esp` one.

2018-11-07 13:25 UTC, Freso commented
(Other than that comment, it looks good. Well done. :))

2018-11-07 19:53 UTC, RowanSkie commented on masterlist.yaml
> -
I'll get right into it. Must've been an overlooked by me.

2018-11-08 09:28 UTC, Freso approved these changes

2018-11-08 09:47 UTC, Freso commented
Merged in with https://github.com/loot/fallout4/commit/bcc8c7accf8e3a4347b03a0b68e2049685653f26. Thanks! :)

2018-11-08 09:47 UTC, closed without merging